import Foundation

enum FeedGenerator {
    static let managedFeedMarker = "<!-- Generated by Recast -->"

    static func write(
        episodes: [Episode],
        channels: [Channel],
        baseURL: String,
        episodesDirectory: URL,
        to feedDirectory: URL
    ) {
        let now = rfc2822(Date())
        let channelNames = channels.map(\.name).joined(separator: ", ")
        let feedDescription = xmlEscape("YouTube talks collected with Recast. Sources: \(channelNames)")
        let showArtworkElement = showArtworkElement(baseURL: baseURL, feedDirectory: feedDirectory)
        let rssImageElement = rssImageElement(baseURL: baseURL, feedDirectory: feedDirectory)

        var items = ""
        for ep in episodes {
            guard let fileName = ep.fileName else { continue }
            let filePath = Paths.episodeFileURL(forRelativePath: fileName, in: episodesDirectory)
            let fileSize = (try? FileManager.default.attributesOfItem(atPath: filePath.path)[.size] as? Int) ?? 0
            let channelName = channels.first(where: { $0.id == ep.channelID })?.name ?? "Unknown"
            let artworkURL = Paths.sharedArtworkURL(forVideoID: ep.videoID, in: episodesDirectory)
            let artworkElement = if FileManager.default.fileExists(atPath: artworkURL.path) {
                "\n                  <itunes:image href=\"\(xmlEscape(feedAssetURL(baseURL: baseURL, fileName: Paths.feedArtworkFileName(forVideoID: ep.videoID))))\"/>"
            } else {
                ""
            }

            items += """

                <item>
                  <title>\(xmlEscape(ep.title))</title>
                  <description>\(xmlEscape("From \(channelName). Watch: https://www.youtube.com/watch?v=\(ep.videoID)"))</description>
                  <enclosure url="\(xmlEscape(feedAssetURL(baseURL: baseURL, fileName: Paths.feedAudioFileName(forVideoID: ep.videoID))))" length="\(fileSize)" type="audio/mpeg"/>
                  <guid isPermaLink="false">\(ep.videoID)</guid>
                  <pubDate>\(rfc2822(ep.publishDate))</pubDate>
                  <itunes:duration>\(formatDuration(ep.durationSeconds))</itunes:duration>
                  <itunes:author>\(xmlEscape(channelName))</itunes:author>\(artworkElement)
                  <link>https://www.youtube.com/watch?v=\(ep.videoID)</link>
                </item>
            """
        }

        let feed = """
        <?xml version="1.0" encoding="UTF-8"?>
        \(managedFeedMarker)
        <rss version="2.0"
             xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd"
             xmlns:atom="http://www.w3.org/2005/Atom">
          <channel>
            <title>Recast</title>
            <description>\(feedDescription)</description>
            <link>\(xmlEscape(baseURL))</link>
            <language>en</language>
            <lastBuildDate>\(now)</lastBuildDate>
            <atom:link href="\(xmlEscape(baseURL))/feed.xml" rel="self" type="application/rss+xml"/>
            <itunes:author>Recast</itunes:author>
            <itunes:summary>\(feedDescription)</itunes:summary>\(showArtworkElement)\(rssImageElement)
            <itunes:category text="Science"/>
            <itunes:explicit>false</itunes:explicit>
        \(items)
          </channel>
        </rss>
        """

        let feedURL = Paths.feedFileURL(in: feedDirectory)
        try? FileManager.default.createDirectory(at: feedDirectory, withIntermediateDirectories: true)
        try? feed.write(to: feedURL, atomically: true, encoding: .utf8)
    }

    // MARK: - Helpers

    static func xmlEscape(_ s: String) -> String {
        s.replacingOccurrences(of: "&", with: "&amp;")
         .replacingOccurrences(of: "<", with: "&lt;")
         .replacingOccurrences(of: ">", with: "&gt;")
         .replacingOccurrences(of: "\"", with: "&quot;")
         .replacingOccurrences(of: "'", with: "&apos;")
    }

    static func rfc2822(_ date: Date) -> String {
        let f = DateFormatter()
        f.locale = Locale(identifier: "en_US_POSIX")
        f.dateFormat = "EEE, dd MMM yyyy HH:mm:ss Z"
        f.timeZone = TimeZone(secondsFromGMT: 0)
        return f.string(from: date)
    }

    static func formatDuration(_ seconds: Int) -> String {
        let h = seconds / 3600
        let m = (seconds % 3600) / 60
        let s = seconds % 60
        return String(format: "%02d:%02d:%02d", h, m, s)
    }

    private static func showArtworkElement(baseURL: String, feedDirectory: URL) -> String {
        let artworkURL = Paths.showArtworkURL(in: feedDirectory)
        guard FileManager.default.fileExists(atPath: artworkURL.path) else { return "" }

        return "\n            <itunes:image href=\"\(xmlEscape(showArtworkURL(baseURL: baseURL)))\"/>"
    }

    private static func rssImageElement(baseURL: String, feedDirectory: URL) -> String {
        let artworkURL = Paths.showArtworkURL(in: feedDirectory)
        guard FileManager.default.fileExists(atPath: artworkURL.path) else { return "" }

        let artworkURLString = xmlEscape(showArtworkURL(baseURL: baseURL))
        return """

            <image>
              <url>\(artworkURLString)</url>
              <title>Recast</title>
              <link>\(xmlEscape(baseURL))</link>
            </image>
        """
    }

    private static func feedAssetURL(baseURL: String, fileName: String) -> String {
        guard let base = URL(string: baseURL) else {
            return "\(baseURL)/\(Paths.feedAssetsDirectoryName)/\(fileName)"
        }

        return base
            .appendingPathComponent(Paths.feedAssetsDirectoryName, isDirectory: true)
            .appendingPathComponent(fileName)
            .absoluteString
    }

    private static func showArtworkURL(baseURL: String) -> String {
        guard let base = URL(string: baseURL) else {
            return "\(baseURL)/\(Paths.showArtworkFileName)"
        }

        return base
            .appendingPathComponent(Paths.showArtworkFileName)
            .absoluteString
    }
}
